# Generated by Django 5.2.17 on 2026-09-09 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('queue', models.CharField(blank=True, default='', max_length=100)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('exception_class', models.CharField(blank=True, default='', max_length=255)),
                ('exception_message', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('retries', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('requeued', 'Requeued'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20)),
                ('requeued_task_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='common_task_status_7bedbc_idx')],
            },
        ),
    ]
