# Generated by Django 4.2.13 on 2026-09-08 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='hireagents', max_length=50)),
                ('connection', models.CharField(default='auth', max_length=50)),
                ('channel', models.CharField(default='whatsapp', max_length=20)),
                ('destination', models.CharField(db_index=True, max_length=255)),
                ('template_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outbound Message',
                'verbose_name_plural': 'Outbound Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
