# Generated by Django 5.2.17 on 2026-09-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('stripe_subscription_id', None), _negated=True), models.Q(('stripe_subscription_id', ''), _negated=True)), fields=('stripe_subscription_id',), name='billing_subscription_stripe_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trialing', 'active'])), fields=('customer',), name='billing_subscription_one_live_per_customer'),
        ),
    ]
