# Generated by Django 5.2.17 on 2026-09-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id__isnull', False)), fields=('provider', 'connection', 'provider_event_id'), name='integrations_webhookevent_provider_event_unique'),
        ),
    ]
