# Generated by Django 5.2.17 on 2026-09-09 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRCapacity',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OCRAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('secret_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=16)),
                ('storage_name', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=32)),
                ('webhook_url', models.URLField(max_length=2048)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('result', models.JSONField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_expires_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_after', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ocr.ocrapikey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OCRUploadReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCRWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_event', to='ocr.ocrjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='ocrjob',
            index=models.Index(fields=['status', 'dispatch_after'], name='ocr_ocrjob_status_c16276_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocrjob',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='ocr_job_org_idempotency_unique'),
        ),
    ]
