# Generated by Django 5.2.17 on 2026-09-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRProviderKeyPoolLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OCRProviderKey',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=32)),
                ('api_key_ciphertext', models.TextField(blank=True)),
                ('api_key_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('api_key_status', models.CharField(db_index=True, max_length=32)),
                ('leased_by', models.CharField(blank=True, max_length=255)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('exhausted_at', models.DateTimeField(blank=True, null=True)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['api_key_status', 'id'], name='ocr_ocrprov_api_key_17f496_idx')],
            },
        ),
    ]
