# Generated by Django 5.2.17 on 2026-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_ocrproviderkeypoollock_ocrproviderkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrproviderkeypoollock',
            name='last_key_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ocrproviderkeypoollock',
            name='last_key_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
